// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnircioicebnrdwifmkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuaXJjaW9pY2VibnJkd2lmbWtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDc3NjYsImV4cCI6MjA2NTY4Mzc2Nn0.laeKOETeVjUDWN8kSb8EkF_vqIyZA67CFkIpIo3p0DM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);